/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.okutonda.okudpdv.views.finance;

import com.okutonda.okudpdv.controllers.ClientController;
import com.okutonda.okudpdv.controllers.FinanceController;
import com.okutonda.okudpdv.controllers.PaymentController;
import com.okutonda.okudpdv.controllers.ProductOrderController;
import com.okutonda.okudpdv.controllers.ShiftController;
import com.okutonda.okudpdv.controllers.UserController;
import com.okutonda.okudpdv.helpers.JpanelLoader;
import com.okutonda.okudpdv.ui.TemaUI;
import com.okutonda.okudpdv.views.payments.JPanelAccountPay;
import com.okutonda.okudpdv.views.payments.JPanelAccountReceive;
import com.okutonda.okudpdv.views.payments.JPanelFluxoBox;
import com.okutonda.okudpdv.views.payments.JPanelPayments;

/**
 *
 * @author kenny
 */
public final class JPanelFinance extends javax.swing.JPanel {

    JpanelLoader jpload = new JpanelLoader();

    /**
     * Creates new form JPanelFinance
     */
    public JPanelFinance() {
        initComponents();

        applyTheme();
        JPanelPayments pPayments = new JPanelPayments();
        jpload.jPanelLoader(jPanelFinanceContent, pPayments);
        jLabelJpanelSelected.setText("PAGAMENTOS");
    }

    private void applyTheme() {
//        TemaCleaner.clearBuilderOverrides(getContentPane());
        // Painel de fundo da janela
//        jPanelSidebar.setBackground(TemaCores.BG_LIGHT);

        TemaUI.aplicarTitulo(jLabelJpanelSelected);
//        jPanelSidebar.setBackground(TemaCores.PRIMARY);
        // Card do login
//        TemaUI.aplicarPainelHeader(jPanelSidebar, TemaCores.PRIMARY);
        // Título
//        TemaUI.aplicarTitulo(jLabelNameCompany);
//        jLabelNameCompany.setForeground(TemaCores.PRIMARY);
        // Labels
//        jLabel1.setForeground(TemaCores.TEXT_DARK);   // "Email:"
//        jLabel2.setForeground(TemaCores.TEXT_DARK);   // "Senha:"
        // Campos
//        TemaUI.aplicarCampoTexto(jTextFieldEmail);
//        TemaUI.aplicarCampoTexto(jPasswordFieldPassword);

        // Botões
//        TemaUI.aplicarBotaoPrimario(jButton1);
//        TemaUI.aplicarBotaoPrimario(jButton2);
//        TemaUI.aplicarBotaoPrimario(jButton3);
//        TemaUI.aplicarBotaoPrimario(jButton4);
//        TemaUI.aplicarBotaoPrimario(jButtonInventoryReport);
//        TemaUI.aplicarBotaoPrimario(jButtonLogin);
//        jButtonSuport.setForeground(TemaCores.TEXT_GRAY);
//        jButtonAbout.setForeground(TemaCores.TEXT_GRAY);
//        jButtonInstall.setForeground(TemaCores.PRIMARY);
//        jButtonCloseScreen.setForeground(TemaCores.ERROR);
        // Status de BD (cor dinâmica) — chama depois de testar a conexão
//        updateDbStatusLabel(this.conn != null);
        // Borda superior/rodapé (opcional)
        // getRootPane().setBorder(new javax.swing.border.MatteBorder(0, 0, 2, 0, TemaCores.PRIMARY));
        // Se o GUI Builder deixou cores hardcoded em initComponents,
        // isso aqui sobrescreve. Se puder, remova as cores fixas no builder.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonPayments = new javax.swing.JButton();
        jButtonAcountReceive = new javax.swing.JButton();
        jButtonAccountPay = new javax.swing.JButton();
        jButtonFluxoBox = new javax.swing.JButton();
        jLabelJpanelSelected = new javax.swing.JLabel();
        jPanelFinanceContent = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(976, 622));

        jToolBar1.setRollover(true);

        jButtonPayments.setBackground(new java.awt.Color(0, 102, 255));
        jButtonPayments.setText("Pagamentos");
        jButtonPayments.setFocusable(false);
        jButtonPayments.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPayments.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentsActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPayments);

        jButtonAcountReceive.setBackground(new java.awt.Color(0, 102, 255));
        jButtonAcountReceive.setText("Contas a Receber");
        jButtonAcountReceive.setFocusable(false);
        jButtonAcountReceive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAcountReceive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAcountReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcountReceiveActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAcountReceive);

        jButtonAccountPay.setBackground(new java.awt.Color(0, 102, 255));
        jButtonAccountPay.setText("Contas a Pagar");
        jButtonAccountPay.setFocusable(false);
        jButtonAccountPay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAccountPay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAccountPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccountPayActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAccountPay);

        jButtonFluxoBox.setBackground(new java.awt.Color(0, 102, 255));
        jButtonFluxoBox.setText("Fluxo de Caixa");
        jButtonFluxoBox.setFocusable(false);
        jButtonFluxoBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFluxoBox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFluxoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFluxoBoxActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonFluxoBox);

        jLabelJpanelSelected.setText("Tela Selecionada");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jLabelJpanelSelected)
                .addGap(86, 86, 86))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelJpanelSelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFinanceContentLayout = new javax.swing.GroupLayout(jPanelFinanceContent);
        jPanelFinanceContent.setLayout(jPanelFinanceContentLayout);
        jPanelFinanceContentLayout.setHorizontalGroup(
            jPanelFinanceContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelFinanceContentLayout.setVerticalGroup(
            jPanelFinanceContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanelFinanceContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFinanceContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcountReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcountReceiveActionPerformed
        // TODO add your handling code here:
        JPanelAccountReceive pAccRec = new JPanelAccountReceive();
        jpload.jPanelLoader(jPanelFinanceContent, pAccRec);
        jLabelJpanelSelected.setText("CONTAS A RECEBER");
    }//GEN-LAST:event_jButtonAcountReceiveActionPerformed

    private void jButtonAccountPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccountPayActionPerformed
        // TODO add your handling code here:
        JPanelAccountPay pAccPay = new JPanelAccountPay();
        jpload.jPanelLoader(jPanelFinanceContent, pAccPay);
        jLabelJpanelSelected.setText("CONTAS A PAGAR");
    }//GEN-LAST:event_jButtonAccountPayActionPerformed

    private void jButtonFluxoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFluxoBoxActionPerformed
        // TODO add your handling code here:
        JPanelFluxoBox pFluxo = new JPanelFluxoBox();
        jpload.jPanelLoader(jPanelFinanceContent, pFluxo);
        jLabelJpanelSelected.setText("FLUXO DE CAIXA");
    }//GEN-LAST:event_jButtonFluxoBoxActionPerformed

    private void jButtonPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentsActionPerformed
        // TODO add your handling code here:
        JPanelPayments pPayments = new JPanelPayments();
        jpload.jPanelLoader(jPanelFinanceContent, pPayments);
        jLabelJpanelSelected.setText("PAGAMENTOS");
    }//GEN-LAST:event_jButtonPaymentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccountPay;
    private javax.swing.JButton jButtonAcountReceive;
    private javax.swing.JButton jButtonFluxoBox;
    private javax.swing.JButton jButtonPayments;
    private javax.swing.JLabel jLabelJpanelSelected;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanelFinanceContent;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
