/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.okutonda.okudpdv.views;

import com.okutonda.okudpdv.views.report.JPanelReport;
import com.okutonda.okudpdv.views.products.JPanelProduct;
import com.okutonda.okudpdv.views.setting.JDialogSetting;
import com.okutonda.okudpdv.views.supplier.JPanelSupplier;
import com.okutonda.okudpdv.views.dashboard.JPanelDashboard;
import com.okutonda.okudpdv.views.pdv.ScreenPdv;
import com.okutonda.okudpdv.views.clients.JPanelClient;
import com.okutonda.okudpdv.views.sales.JPanelSales;
import com.okutonda.okudpdv.views.users.JPanelUser;
import com.okutonda.okudpdv.views.login.ScreenLogin;
import com.formdev.flatlaf.FlatLightLaf;
import com.okutonda.okudpdv.controllers.AdminRoot;
import com.okutonda.okudpdv.controllers.UserController;
import com.okutonda.okudpdv.utilities.CompanySession;
import com.okutonda.okudpdv.utilities.JpanelLoader;
import com.okutonda.okudpdv.utilities.UserSession;
import com.okutonda.okudpdv.views.finance.JPanelFinance;
import com.okutonda.okudpdv.views.stock.JPanelStock;
import com.okutonda.okudpdv.views.suport.JDialogValidateLicence;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author kenny
 */
public final class ScreenMain extends javax.swing.JFrame {

    JpanelLoader jpload = new JpanelLoader();
    UserSession session;
    CompanySession companySession;
//    ShiftSession shiftSession;
    UserController userController;
//    ShiftController shiftController = new ShiftController();
    AdminRoot root = new AdminRoot();

    public void roles() {
        switch (session.getUser().getProfile()) {
            case "admin":
                break;
            case "user":
                this.jToggleButtonUsers.setEnabled(false);
                this.jToggleButtonUsers.setEnabled(false);
                this.jButtonSettings.setEnabled(false);
                this.jButtonSettings.setEnabled(false);
                break;
            case "seller":
                this.jToggleButtonUsers.setEnabled(false);
                this.jToggleButtonSideBarSupplier.setEnabled(false);
                this.jButtonSettings.setEnabled(false);
                break;
            case "manager":
                this.jToggleButtonUsers.setEnabled(false);
                this.jToggleButtonSideBarSupplier.setEnabled(false);
//                this.jButtonOpenPDV.setEnabled(false);
                this.jButtonSettings.setEnabled(false);
                break;
            default:
                break;
        }
    }

    /**
     * Creates new form ScreenMain
     */
    public ScreenMain() {
        initComponents();
        userController = new UserController();
        session = UserSession.getInstance();
        companySession = CompanySession.getInstance();

        if (session != null || session.getUser().getStatus().equals("ativo") == true) {
//            JOptionPane.showMessageDialog(null, "sessio: " + session.getUsername());
            this.setExtendedState(ScreenMain.MAXIMIZED_BOTH);
            roles();
            JPanelDashboard pDashboard = new JPanelDashboard();
            jpload.jPanelLoader(jPanelContent, pDashboard);
            jLabelUserLogin.setText(session.getUser().getName());
            jLabelUserLoginProfil.setText(session.getUser().getProfile());
            jLabelNameCompany.setText(companySession.getName());
        } else {
//            new ScreenLogin().setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSideBar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToggleButtonUsers = new javax.swing.JToggleButton();
        jToggleButtonSideBarDashboard = new javax.swing.JToggleButton();
        jToggleButtonSideBarClient = new javax.swing.JToggleButton();
        jToggleButtonSideBarProduct = new javax.swing.JToggleButton();
        jToggleButtonSideBarSales = new javax.swing.JToggleButton();
        jToggleButtonSideBarPayment = new javax.swing.JToggleButton();
        jToggleButtonSideBarSupplier = new javax.swing.JToggleButton();
        jToggleButtonSideBarReport = new javax.swing.JToggleButton();
        jLabelUserLogin = new javax.swing.JLabel();
        jLabelUserLoginProfil = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jToggleButtonSideBarDashboard1 = new javax.swing.JToggleButton();
        jLabelNameCompany = new javax.swing.JLabel();
        jLabelDatetime = new javax.swing.JLabel();
        jToggleButtonStock = new javax.swing.JToggleButton();
        jLabelNamePanelOpen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(242, 242, 242));
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(170, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 700));
        jPanel1.setRequestFocusEnabled(false);

        buttonGroupSideBar.add(jToggleButtonUsers);
        jToggleButtonUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/people_3239045.png"))); // NOI18N
        jToggleButtonUsers.setText("Usuario");
        jToggleButtonUsers.setBorderPainted(false);
        jToggleButtonUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonUsersActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarDashboard);
        jToggleButtonSideBarDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard-interface_5715555.png"))); // NOI18N
        jToggleButtonSideBarDashboard.setSelected(true);
        jToggleButtonSideBarDashboard.setText("Dashboard");
        jToggleButtonSideBarDashboard.setBorderPainted(false);
        jToggleButtonSideBarDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarDashboardActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarClient);
        jToggleButtonSideBarClient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/people_3239045.png"))); // NOI18N
        jToggleButtonSideBarClient.setText("Clientes");
        jToggleButtonSideBarClient.setBorderPainted(false);
        jToggleButtonSideBarClient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarClientActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarProduct);
        jToggleButtonSideBarProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/box-open_9246330.png"))); // NOI18N
        jToggleButtonSideBarProduct.setText("Produtos");
        jToggleButtonSideBarProduct.setBorderPainted(false);
        jToggleButtonSideBarProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarProductActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarSales);
        jToggleButtonSideBarSales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shop_6895262.png"))); // NOI18N
        jToggleButtonSideBarSales.setText("Vendas");
        jToggleButtonSideBarSales.setBorderPainted(false);
        jToggleButtonSideBarSales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarSalesActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarPayment);
        jToggleButtonSideBarPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report_1321938.png"))); // NOI18N
        jToggleButtonSideBarPayment.setText("Financeiro");
        jToggleButtonSideBarPayment.setBorderPainted(false);
        jToggleButtonSideBarPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarPaymentActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarSupplier);
        jToggleButtonSideBarSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/supplier_17241534.png"))); // NOI18N
        jToggleButtonSideBarSupplier.setText("Fornecedores");
        jToggleButtonSideBarSupplier.setBorderPainted(false);
        jToggleButtonSideBarSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarSupplierActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarReport);
        jToggleButtonSideBarReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report_1321938.png"))); // NOI18N
        jToggleButtonSideBarReport.setText("Relatorio");
        jToggleButtonSideBarReport.setBorderPainted(false);
        jToggleButtonSideBarReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarReportActionPerformed(evt);
            }
        });

        jLabelUserLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserLogin.setText("Usuario");

        jLabelUserLoginProfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUserLoginProfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserLoginProfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserLoginProfil.setText("Perfil");

        jButtonSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power-button_12080793.png"))); // NOI18N
        jButtonSair.setBorderPainted(false);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonSettings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/setting_2626897.png"))); // NOI18N
        jButtonSettings.setBorderPainted(false);
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });

        buttonGroupSideBar.add(jToggleButtonSideBarDashboard1);
        jToggleButtonSideBarDashboard1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonSideBarDashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cashier_4429519.png"))); // NOI18N
        jToggleButtonSideBarDashboard1.setText("Faturação");
        jToggleButtonSideBarDashboard1.setBorderPainted(false);
        jToggleButtonSideBarDashboard1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonSideBarDashboard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSideBarDashboard1ActionPerformed(evt);
            }
        });

        jLabelNameCompany.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNameCompany.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNameCompany.setText("LOGO");

        jLabelDatetime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDatetime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDatetime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatetime.setText("data atual");

        buttonGroupSideBar.add(jToggleButtonStock);
        jToggleButtonStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart_14572403.png"))); // NOI18N
        jToggleButtonStock.setText("Estoque");
        jToggleButtonStock.setBorderPainted(false);
        jToggleButtonStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButtonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonStockActionPerformed(evt);
            }
        });

        jLabelNamePanelOpen.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabelNamePanelOpen.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNamePanelOpen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNamePanelOpen.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonSideBarDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSideBarClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSideBarProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSideBarDashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSideBarSales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSideBarPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSideBarSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jToggleButtonSideBarReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelUserLoginProfil, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(jLabelDatetime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelNameCompany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNamePanelOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNameCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNamePanelOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserLoginProfil)
                .addGap(2, 2, 2)
                .addComponent(jLabelDatetime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonSideBarDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonSideBarDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonSideBarClient, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonSideBarProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonStock, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jToggleButtonSideBarSales, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonSideBarPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonSideBarSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonSideBarReport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jToggleButtonSideBarClient, jToggleButtonSideBarDashboard, jToggleButtonSideBarPayment, jToggleButtonSideBarProduct, jToggleButtonSideBarReport, jToggleButtonSideBarSales, jToggleButtonSideBarSupplier, jToggleButtonUsers});

        jScrollPane2.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanelContent.setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanelContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1040, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //Verificar as sessao do usuario
        if (session.getUser().getStatus().equals("inativo") == true) {
            new ScreenLogin().setVisible(true);
            this.dispose();
        } else {
            if (root.getStatusLicence() == false) {
                JDialogValidateLicence dialogLicence = new JDialogValidateLicence(this, rootPaneCheckingEnabled);
                dialogLicence.setVisible(true);
            } else {
                Date date = new Date();
                DateFormat dateF = DateFormat.getDateInstance(DateFormat.SHORT);
                jLabelDatetime.setText(dateF.format(date));
            }

        }
    }//GEN-LAST:event_formWindowActivated

    private void jToggleButtonSideBarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarClientActionPerformed
        // TODO add your handling code here:
        JPanelClient pClient = new JPanelClient();
        jpload.jPanelLoader(jPanelContent, pClient);
        jLabelNamePanelOpen.setText("CLIENTES");

    }//GEN-LAST:event_jToggleButtonSideBarClientActionPerformed

    private void jToggleButtonSideBarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarProductActionPerformed
        // TODO add your handling code here:
        JPanelProduct pProduct = new JPanelProduct();
        jpload.jPanelLoader(jPanelContent, pProduct);
        jLabelNamePanelOpen.setText("PRODUTO");
    }//GEN-LAST:event_jToggleButtonSideBarProductActionPerformed

    private void jToggleButtonSideBarPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarPaymentActionPerformed
        // TODO add your handling code here:
        JPanelFinance pFinanec = new JPanelFinance();
        jpload.jPanelLoader(jPanelContent, pFinanec);
        jLabelNamePanelOpen.setText("FINANCEIRO");
//        JPanelPayment pPayment = new JPanelPayment();
//        jpload.jPanelLoader(jPanelContent, pPayment);
//        jLabelNamePanelOpen.setText("PAGAMENTOS");
    }//GEN-LAST:event_jToggleButtonSideBarPaymentActionPerformed

    private void jToggleButtonSideBarSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarSalesActionPerformed
        // TODO add your handling code here:
        JPanelSales pSales = new JPanelSales();
        jpload.jPanelLoader(jPanelContent, pSales);
        jLabelNamePanelOpen.setText("VENDAS");
    }//GEN-LAST:event_jToggleButtonSideBarSalesActionPerformed

    private void jToggleButtonSideBarSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarSupplierActionPerformed
        // TODO add your handling code here:
        JPanelSupplier pSupplier = new JPanelSupplier();
        jpload.jPanelLoader(jPanelContent, pSupplier);
        jLabelNamePanelOpen.setText("FORNECEDORES");
    }//GEN-LAST:event_jToggleButtonSideBarSupplierActionPerformed

    private void jToggleButtonSideBarReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarReportActionPerformed
        // TODO add your handling code here:
        JPanelReport pReport = new JPanelReport();
        jpload.jPanelLoader(jPanelContent, pReport);
        jLabelNamePanelOpen.setText("RELATORIOS");
    }//GEN-LAST:event_jToggleButtonSideBarReportActionPerformed

    private void jToggleButtonSideBarDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarDashboardActionPerformed
        // TODO add your handling code here:
        JPanelDashboard pDashboard = new JPanelDashboard();
        jpload.jPanelLoader(jPanelContent, pDashboard);
        jLabelNamePanelOpen.setText("DASHBOARD");
    }//GEN-LAST:event_jToggleButtonSideBarDashboardActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
            if (userController.logout()) {
                new ScreenLogin().setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jToggleButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonUsersActionPerformed
        // TODO add your handling code here:
        JPanelUser pUser = new JPanelUser();
        jpload.jPanelLoader(jPanelContent, pUser);
        jLabelNamePanelOpen.setText("USUARIO");
    }//GEN-LAST:event_jToggleButtonUsersActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // TODO add your handling code here:
        new JDialogSetting(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jToggleButtonSideBarDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSideBarDashboard1ActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Abrir o PDV ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            new ScreenPdv().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jToggleButtonSideBarDashboard1ActionPerformed

    private void jToggleButtonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonStockActionPerformed
        // TODO add your handling code here:
        JPanelStock pStock = new JPanelStock();
        jpload.jPanelLoader(jPanelContent, pStock);
        jLabelNamePanelOpen.setText("ESTOQUE");
    }//GEN-LAST:event_jToggleButtonStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSideBar;
    private javax.swing.JButton jButtonSair;
    public javax.swing.JButton jButtonSettings;
    private javax.swing.JLabel jLabelDatetime;
    private javax.swing.JLabel jLabelNameCompany;
    private javax.swing.JLabel jLabelNamePanelOpen;
    public static javax.swing.JLabel jLabelUserLogin;
    public static javax.swing.JLabel jLabelUserLoginProfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JToggleButton jToggleButtonSideBarClient;
    public javax.swing.JToggleButton jToggleButtonSideBarDashboard;
    public javax.swing.JToggleButton jToggleButtonSideBarDashboard1;
    public javax.swing.JToggleButton jToggleButtonSideBarPayment;
    public javax.swing.JToggleButton jToggleButtonSideBarProduct;
    public javax.swing.JToggleButton jToggleButtonSideBarReport;
    public javax.swing.JToggleButton jToggleButtonSideBarSales;
    public javax.swing.JToggleButton jToggleButtonSideBarSupplier;
    public javax.swing.JToggleButton jToggleButtonStock;
    public javax.swing.JToggleButton jToggleButtonUsers;
    // End of variables declaration//GEN-END:variables
}
