/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.okutonda.okudpdv.views.entity;

import com.okutonda.okudpdv.controllers.ClientController;
import com.okutonda.okudpdv.controllers.SupplierController;
import com.okutonda.okudpdv.data.entities.Clients;
import com.okutonda.okudpdv.data.entities.Supplier;
import com.okutonda.okudpdv.helpers.JpanelLoader;
import com.okutonda.okudpdv.helpers.UserSession;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author kenny
 */
public final class JPanelEntity extends javax.swing.JPanel {

//    JpanelLoader jpload = new JpanelLoader();
    private final JpanelLoader jpload = new JpanelLoader();
    private final ClientController clientController = new ClientController();
    private final SupplierController supplierController = new SupplierController();
    private final UserSession session;

    /**
     * Creates new form JPanelClient
     */
    public JPanelEntity() {
        initComponents();
//        applyTheme();
        session = UserSession.getInstance();
        inicializarComponentes();
//         applyTheme();
        JPanelClients pClients = new JPanelClients();
        jpload.jPanelLoader(jPanelEntityContent, pClients);
        jLabelJpanelSelected.setText("CLIENTES");
    }

//    private void applyTheme() {
//        TemaCleaner.clearBuilderOverrides(jPanelClient);
//        // Painel de fundo da janela
//        jPanelClient.setBackground(TemaCores.BG_LIGHT);
//    }
    private void inicializarComponentes() {
        // Carregar estatísticas iniciais
        carregarEstatisticas();

        // Carregar painel de clientes por padrão
        JPanelClients pClients = new JPanelClients();
        jpload.jPanelLoader(jPanelEntityContent, pClients);
        jLabelJpanelSelected.setText("CLIENTES");
    }

    private void carregarEstatisticas() {
        try {
            // Carregar estatísticas em uma thread separada para não travar a UI
            SwingUtilities.invokeLater(() -> {
                try {
                    // Estatísticas de Clientes
                    List<Clients> todosClientes = clientController.getAll();
                    List<Clients> clientesAtivos = clientController.getActiveClients();

                    int totalClientes = todosClientes.size();
                    int clientesAtivosCount = clientesAtivos.size();
                    int clientesInativosCount = totalClientes - clientesAtivosCount;

                    jLabelTotalClients.setText(String.valueOf(totalClientes));
                    jLabel9clientAtive.setText(String.valueOf(clientesAtivosCount));
                    jLabelClientInative.setText(String.valueOf(clientesInativosCount));

                    // Estatísticas de Fornecedores
                    List<Supplier> todosFornecedores = supplierController.listarTodos();
                    List<Supplier> fornecedoresAtivos = supplierController.listarAtivos();

                    int totalFornecedores = todosFornecedores.size();
                    int fornecedoresAtivosCount = fornecedoresAtivos.size();
                    int fornecedoresInativosCount = totalFornecedores - fornecedoresAtivosCount;

                    jLabel8SupplierTotal.setText(String.valueOf(totalFornecedores));
                    jLabelSuplierAtive.setText(String.valueOf(fornecedoresAtivosCount));
                    jLabelSupplierInative.setText(String.valueOf(fornecedoresInativosCount));

                } catch (Exception e) {
                    System.err.println("❌ Erro ao carregar estatísticas: " + e.getMessage());
                    // Definir valores padrão em caso de erro
                    definirValoresPadrao();
                }
            });

        } catch (Exception e) {
            System.err.println("❌ Erro ao iniciar carregamento de estatísticas: " + e.getMessage());
            definirValoresPadrao();
        }
    }

    private void definirValoresPadrao() {
        jLabelTotalClients.setText("0");
        jLabel9clientAtive.setText("0");
        jLabelClientInative.setText("0");
        jLabel8SupplierTotal.setText("0");
        jLabelSuplierAtive.setText("0");
        jLabelSupplierInative.setText("0");
    }
    // Método público para atualizar estatísticas de outros componentes

    public void atualizarEstatisticas() {
        carregarEstatisticas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonClients = new javax.swing.JButton();
        jButtonSuppliers = new javax.swing.JButton();
        jLabelJpanelSelected = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotalClients = new javax.swing.JLabel();
        jLabel8SupplierTotal = new javax.swing.JLabel();
        jLabel9clientAtive = new javax.swing.JLabel();
        jLabelClientInative = new javax.swing.JLabel();
        jLabelSuplierAtive = new javax.swing.JLabel();
        jLabelSupplierInative = new javax.swing.JLabel();
        jPanelEntityContent = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jToolBar1.setRollover(true);

        jButtonClients.setBackground(new java.awt.Color(0, 102, 255));
        jButtonClients.setText("Clientes");
        jButtonClients.setFocusable(false);
        jButtonClients.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClients.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientsActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonClients);

        jButtonSuppliers.setBackground(new java.awt.Color(0, 102, 255));
        jButtonSuppliers.setText("Fornecedores");
        jButtonSuppliers.setFocusable(false);
        jButtonSuppliers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSuppliers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppliersActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSuppliers);

        jLabelJpanelSelected.setText("Tela Selecionada");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelJpanelSelected)
                .addGap(86, 86, 86))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelJpanelSelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Clinete Ativos");

        jLabel2.setText("Total de cliente");

        jLabel3.setText("Total Fornecedores");

        jLabel4.setText("Fornecedores Ativo");

        jLabel5.setText("Clinete  Inativos");

        jLabel6.setText("Fornecedores inativos");

        jLabelTotalClients.setText("Total de cliente");

        jLabel8SupplierTotal.setText("Total Fornecedores");

        jLabel9clientAtive.setText("Clinete Ativos");

        jLabelClientInative.setText("Clinete  Inativos");

        jLabelSuplierAtive.setText("Fornecedores Ativo");

        jLabelSupplierInative.setText("Fornecedores inativos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelTotalClients))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8SupplierTotal))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9clientAtive))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabelClientInative))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSuplierAtive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSupplierInative)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalClients)
                    .addComponent(jLabel8SupplierTotal)
                    .addComponent(jLabel9clientAtive)
                    .addComponent(jLabelClientInative)
                    .addComponent(jLabelSuplierAtive)
                    .addComponent(jLabelSupplierInative))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEntityContentLayout = new javax.swing.GroupLayout(jPanelEntityContent);
        jPanelEntityContent.setLayout(jPanelEntityContentLayout);
        jPanelEntityContentLayout.setHorizontalGroup(
            jPanelEntityContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelEntityContentLayout.setVerticalGroup(
            jPanelEntityContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEntityContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelEntityContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientsActionPerformed
        // TODO add your handling code here:
        JPanelClients pClient = new JPanelClients();
        jpload.jPanelLoader(jPanelEntityContent, pClient);
        jLabelJpanelSelected.setText("CLIENTES");

        // Atualizar estatísticas quando mudar para fornecedores
        carregarEstatisticas();
    }//GEN-LAST:event_jButtonClientsActionPerformed

    private void jButtonSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppliersActionPerformed
        // TODO add your handling code here:
        JPanelSuppliers pSupp = new JPanelSuppliers();
        jpload.jPanelLoader(jPanelEntityContent, pSupp);
        jLabelJpanelSelected.setText("FORNECEDORES");
    }//GEN-LAST:event_jButtonSuppliersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClients;
    private javax.swing.JButton jButtonSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8SupplierTotal;
    private javax.swing.JLabel jLabel9clientAtive;
    private javax.swing.JLabel jLabelClientInative;
    private javax.swing.JLabel jLabelJpanelSelected;
    private javax.swing.JLabel jLabelSuplierAtive;
    private javax.swing.JLabel jLabelSupplierInative;
    private javax.swing.JLabel jLabelTotalClients;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanelEntityContent;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
