/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.okutonda.okudpdv.views.entity;

import com.okutonda.okudpdv.controllers.SupplierController;
import com.okutonda.okudpdv.data.entities.Supplier;
import com.okutonda.okudpdv.helpers.UserSession;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hr
 */
public class JPanelSuppliers extends javax.swing.JPanel {

    private final SupplierController supplierController;
    private final UserSession session;

    /**
     * Creates new form JPanelSuppliers
     */
    public JPanelSuppliers() {
        initComponents();
        supplierController = new SupplierController();
        session = UserSession.getInstance();
        listSuppliers();
    }

    public void listSuppliers() {
        try {
            List<Supplier> list = supplierController.listarTodos();
            DefaultTableModel data = (DefaultTableModel) jTableSuppliers.getModel();
            data.setNumRows(0);

            for (Supplier supplier : list) {
                String status = supplier.getStatus() == 1 ? "Ativo" : "Inativo";
                data.addRow(new Object[]{
                    supplier.getId(),
                    supplier.getNif(),
                    supplier.getName(),
                    supplier.getEmail(),
                    supplier.getPhone(),
                    supplier.getAddress(),
                    supplier.getZipCode(),
                    status
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao carregar fornecedores: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void filterSupplierList(String txt) {
        try {
            List<Supplier> list = supplierController.filtrar(txt);
            DefaultTableModel data = (DefaultTableModel) jTableSuppliers.getModel();
            data.setNumRows(0);

            for (Supplier supplier : list) {
                String status = supplier.getStatus() == 1 ? "Ativo" : "Inativo";
                data.addRow(new Object[]{
                    supplier.getId(),
                    supplier.getNif(),
                    supplier.getName(),
                    supplier.getEmail(),
                    supplier.getPhone(),
                    supplier.getAddress(),
                    supplier.getZipCode(),
                    status
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao filtrar fornecedores: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSearchSupplier = new javax.swing.JPanel();
        jTextFieldFilterNameTable = new javax.swing.JTextField();
        jButtonAlterSeleted = new javax.swing.JButton();
        jButtonDeleteSelected = new javax.swing.JButton();
        jButtonOpenFormSupplier = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSuppliers = new javax.swing.JTable();
        jButtonViewSupplierSelected = new javax.swing.JButton();

        jTextFieldFilterNameTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFilterNameTableKeyReleased(evt);
            }
        });

        jButtonAlterSeleted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit Pencil.png"))); // NOI18N
        jButtonAlterSeleted.setText("Alterar");
        jButtonAlterSeleted.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterSeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterSeletedActionPerformed(evt);
            }
        });

        jButtonDeleteSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash Can.png"))); // NOI18N
        jButtonDeleteSelected.setText("Excluir");
        jButtonDeleteSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSelectedActionPerformed(evt);
            }
        });

        jButtonOpenFormSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus.png"))); // NOI18N
        jButtonOpenFormSupplier.setText("Adicionar");
        jButtonOpenFormSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOpenFormSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFormSupplierActionPerformed(evt);
            }
        });

        jTableSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIF", "Nome", "Email", "Telefone", "Endereço", "Zip", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSuppliersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSuppliers);

        jButtonViewSupplierSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Binoculars.png"))); // NOI18N
        jButtonViewSupplierSelected.setText("Ver");
        jButtonViewSupplierSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonViewSupplierSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewSupplierSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchSupplierLayout = new javax.swing.GroupLayout(jPanelSearchSupplier);
        jPanelSearchSupplier.setLayout(jPanelSearchSupplierLayout);
        jPanelSearchSupplierLayout.setHorizontalGroup(
            jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelSearchSupplierLayout.createSequentialGroup()
                        .addComponent(jTextFieldFilterNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(jButtonOpenFormSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonViewSupplierSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterSeleted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteSelected)))
                .addGap(0, 0, 0))
        );
        jPanelSearchSupplierLayout.setVerticalGroup(
            jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchSupplierLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFilterNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenFormSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterSeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewSupplierSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelSearchSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelSearchSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFilterNameTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterNameTableKeyReleased
        // TODO add your handling code here:
        String txt = jTextFieldFilterNameTable.getText();
        if (!txt.isEmpty()) {
            filterSupplierList(txt);
        } else {
            listSuppliers();
        }
    }//GEN-LAST:event_jTextFieldFilterNameTableKeyReleased

    private void jButtonAlterSeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterSeletedActionPerformed
        // TODO add your handling code here:
        int value = 0;
        try {
            value = (int) jTableSuppliers.getValueAt(jTableSuppliers.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (value > 0) {
                JDialogFormSupplier formUser = new JDialogFormSupplier(null, true);
                formUser.setSupplier(value);
                formUser.setVisible(true);
                Boolean resp = formUser.getResponse();
                if (resp == true) {
                    JOptionPane.showMessageDialog(null, "Usuario salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    listSuppliers();
                }
            }
        }
    }//GEN-LAST:event_jButtonAlterSeletedActionPerformed

    private void jButtonDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSelectedActionPerformed
        // TODO add your handling code here:
        int id = 0;
        try {
            id = (int) jTableSuppliers.getValueAt(jTableSuppliers.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (id > 0) {
                Supplier client = supplierController.getById(id);
                int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Deletar," + client.getName() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (sair == JOptionPane.YES_OPTION) {
                    if (supplierController.delete(id)) {
                        JOptionPane.showMessageDialog(null, "suppliers excluido com Sucesso!!");
                        listSuppliers();
                    }
                }
            }
        }

        //        int id = Integer.parseInt(jTableSuppliers.getValueAt(jTableSuppliers.getSelectedRow(), 0).toString());
        //        Supplier client = supplierController.getId(id);
        //        //        JOptionPane.showMessageDialog(null, "Cliente :" + client.getName());
        //        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Deletar," + client.getName() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
        //        if (sair == JOptionPane.YES_OPTION) {
        //            if (supplierController.deleteId(id)) {
        //                JOptionPane.showMessageDialog(null, "suppliers excluido com Sucesso!!");
        //                listSuppliers();
        //            }
        //        }
    }//GEN-LAST:event_jButtonDeleteSelectedActionPerformed

    private void jButtonOpenFormSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFormSupplierActionPerformed
        // TODO add your handling code here:
        JDialogFormSupplier formSupplier = new JDialogFormSupplier(null, true);
        formSupplier.setVisible(true);
        Boolean resp = formSupplier.getResponse();
        if (resp != null && resp) {
            JOptionPane.showMessageDialog(null, "Fornecedor salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            listSuppliers();
        }
    }//GEN-LAST:event_jButtonOpenFormSupplierActionPerformed

    private void jTableSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSuppliersMouseClicked
        // TODO add your handling code here:
        // Duplo clique para editar
        if (evt.getClickCount() == 2) {
            jButtonAlterSeletedActionPerformed(null);
        }
    }//GEN-LAST:event_jTableSuppliersMouseClicked

    private void jButtonViewSupplierSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewSupplierSelectedActionPerformed
        // TODO add your handling code here:
        int id = 0;
        try {
            id = (int) jTableSuppliers.getValueAt(jTableSuppliers.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (id > 0) {
            JDialogViewSupplier viewSupplier = new JDialogViewSupplier(null, true);
            viewSupplier.setData(id);
            viewSupplier.setVisible(true);
        }
    }//GEN-LAST:event_jButtonViewSupplierSelectedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAlterSeleted;
    public javax.swing.JButton jButtonDeleteSelected;
    private javax.swing.JButton jButtonOpenFormSupplier;
    private javax.swing.JButton jButtonViewSupplierSelected;
    private javax.swing.JPanel jPanelSearchSupplier;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSuppliers;
    private javax.swing.JTextField jTextFieldFilterNameTable;
    // End of variables declaration//GEN-END:variables
}
