/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.okutonda.okudpdv.views.entity;

import com.okutonda.okudpdv.controllers.ClientController;
import com.okutonda.okudpdv.data.entities.Clients;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hr
 */
public class JPanelClients extends javax.swing.JPanel {

    private final ClientController clientController;

    /**
     * Creates new form JPanelClients
     */
    public JPanelClients() {
        initComponents();

        clientController = new ClientController();
        listClients();
    }

    public void listClients() {
        try {
            List<Clients> list = clientController.getAll();
            DefaultTableModel data = (DefaultTableModel) jTableClients.getModel();
            data.setNumRows(0);

            for (Clients client : list) {
                String status = client.getStatus() == 1 ? "Ativo" : "Inativo";
                String isDefault = client.getIsDefault() == 1 ? "Sim" : "Não";

                data.addRow(new Object[]{
                    client.getId(),
                    client.getNif(),
                    client.getName(),
                    client.getEmail(),
                    client.getPhone(),
                    client.getAddress(),
                    client.getZipCode(),
                    status,
                    isDefault
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao carregar clientes: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void filterListClients(String txt) {
        try {
            List<Clients> list = clientController.filter(txt);
            DefaultTableModel data = (DefaultTableModel) jTableClients.getModel();
            data.setNumRows(0);

            for (Clients client : list) {
                String status = client.getStatus() == 1 ? "Ativo" : "Inativo";
                String isDefault = client.getIsDefault() == 1 ? "Sim" : "Não";

                data.addRow(new Object[]{
                    client.getId(),
                    client.getNif(),
                    client.getName(),
                    client.getEmail(),
                    client.getPhone(),
                    client.getAddress(),
                    client.getZipCode(),
                    status,
                    isDefault
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao filtrar clientes: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClient = new javax.swing.JPanel();
        jButtonFilterClientNameTable = new javax.swing.JButton();
        jTextFieldFilterClientNameTable = new javax.swing.JTextField();
        jButtonAlterClientSeletedTable = new javax.swing.JButton();
        jButtonDeleteClientSelectedTable = new javax.swing.JButton();
        jButtonCreateNewClient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClients = new javax.swing.JTable();
        jButtonCreateViewClient = new javax.swing.JButton();

        jPanelClient.setPreferredSize(new java.awt.Dimension(900, 600));

        jButtonFilterClientNameTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        jButtonFilterClientNameTable.setText("Pesquisar");
        jButtonFilterClientNameTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFilterClientNameTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterClientNameTableActionPerformed(evt);
            }
        });

        jTextFieldFilterClientNameTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFilterClientNameTableKeyReleased(evt);
            }
        });

        jButtonAlterClientSeletedTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit Pencil.png"))); // NOI18N
        jButtonAlterClientSeletedTable.setText("Editar");
        jButtonAlterClientSeletedTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterClientSeletedTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterClientSeletedTableActionPerformed(evt);
            }
        });

        jButtonDeleteClientSelectedTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash Can.png"))); // NOI18N
        jButtonDeleteClientSelectedTable.setText("Excluir");
        jButtonDeleteClientSelectedTable.setToolTipText("Apagar Cliente");
        jButtonDeleteClientSelectedTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteClientSelectedTable.setSelected(true);
        jButtonDeleteClientSelectedTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteClientSelectedTableActionPerformed(evt);
            }
        });

        jButtonCreateNewClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus.png"))); // NOI18N
        jButtonCreateNewClient.setText("Adicionar");
        jButtonCreateNewClient.setToolTipText("Cadastrar Cliente");
        jButtonCreateNewClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCreateNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateNewClientActionPerformed(evt);
            }
        });

        jTableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NIF", "Nome", "Email", "Telefone", "Endereço", "Zip", "Status", "Padrão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClients);

        jButtonCreateViewClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Binoculars.png"))); // NOI18N
        jButtonCreateViewClient.setText("Ver");
        jButtonCreateViewClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCreateViewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateViewClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientLayout = new javax.swing.GroupLayout(jPanelClient);
        jPanelClient.setLayout(jPanelClientLayout);
        jPanelClientLayout.setHorizontalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanelClientLayout.createSequentialGroup()
                        .addComponent(jTextFieldFilterClientNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFilterClientNameTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButtonCreateNewClient)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreateViewClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterClientSeletedTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteClientSelectedTable, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
        );
        jPanelClientLayout.setVerticalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFilterClientNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilterClientNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreateNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterClientSeletedTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteClientSelectedTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreateViewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelClient, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelClient, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilterClientNameTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterClientNameTableActionPerformed
        // TODO add your handling code here:
        String txt = jTextFieldFilterClientNameTable.getText();
        if (!txt.isEmpty()) {
            filterListClients(txt);
        } else {
            listClients();
        }
    }//GEN-LAST:event_jButtonFilterClientNameTableActionPerformed

    private void jTextFieldFilterClientNameTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterClientNameTableKeyReleased
        // TODO add your handling code here:
        String txt = jTextFieldFilterClientNameTable.getText();
        if (!txt.isEmpty()) {
            filterListClients(txt);
        } else {
            listClients();
        }
    }//GEN-LAST:event_jTextFieldFilterClientNameTableKeyReleased

    private void jButtonAlterClientSeletedTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterClientSeletedTableActionPerformed
        // TODO add your handling code here:
        int value = 0;
        try {
            value = (int) jTableClients.getValueAt(jTableClients.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (value > 0) {
            JDialogFormClient formClient = new JDialogFormClient(null, true);
            formClient.setClient(value);
            formClient.setVisible(true);
            Boolean resp = formClient.getResponse();
            if (resp != null && resp) {
                JOptionPane.showMessageDialog(null, "Cliente salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                listClients();
            }
        }
    }//GEN-LAST:event_jButtonAlterClientSeletedTableActionPerformed

    private void jButtonDeleteClientSelectedTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteClientSelectedTableActionPerformed
        // TODO add your handling code here:
        int id = 0;
        try {
            id = (int) jTableClients.getValueAt(jTableClients.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (id > 0) {
            Clients client = clientController.getById(id);
            if (client == null) {
                JOptionPane.showMessageDialog(null, "Cliente não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(null,
                    "Tem certeza que deseja excluir " + client.getName() + "?",
                    "Atenção", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (clientController.deleteById(id)) {
                    JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!!");
                    listClients();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonDeleteClientSelectedTableActionPerformed

    private void jButtonCreateNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateNewClientActionPerformed
        // TODO add your handling code here:
        JDialogFormClient formClient = new JDialogFormClient(null, true);
        formClient.setVisible(true);
        Boolean resp = formClient.getResponse();
        if (resp != null && resp) {
            JOptionPane.showMessageDialog(null, "Cliente salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            listClients();
        }
    }//GEN-LAST:event_jButtonCreateNewClientActionPerformed

    private void jTableClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jButtonAlterClientSeletedTableActionPerformed(null);
        }
    }//GEN-LAST:event_jTableClientsMouseClicked

    private void jButtonCreateViewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateViewClientActionPerformed
        // TODO add your handling code here:
        int id = 0;
        try {
            id = (int) jTableClients.getValueAt(jTableClients.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (id > 0) {
            JDialogViewClient viewClient = new JDialogViewClient(null, true);
            viewClient.setData(id);
            viewClient.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCreateViewClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAlterClientSeletedTable;
    private javax.swing.JButton jButtonCreateNewClient;
    private javax.swing.JButton jButtonCreateViewClient;
    public javax.swing.JButton jButtonDeleteClientSelectedTable;
    private javax.swing.JButton jButtonFilterClientNameTable;
    private javax.swing.JPanel jPanelClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClients;
    private javax.swing.JTextField jTextFieldFilterClientNameTable;
    // End of variables declaration//GEN-END:variables
}
