/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.okutonda.okudpdv.views.products;

import com.okutonda.okudpdv.controllers.ProductController;
import com.okutonda.okudpdv.controllers.SupplierController;
import com.okutonda.okudpdv.models.Product;
import com.okutonda.okudpdv.models.Supplier;
import com.okutonda.okudpdv.views.form.JDialogFormPurchase;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kenny
 */
public final class JPanelProduct extends javax.swing.JPanel {

    ProductController productController = new ProductController();
    SupplierController supplierController = new SupplierController();

    /**
     * Creates new form JPanelProduct
     */
    public JPanelProduct() {
        initComponents();
        listProducts();
        listProductsInventory();
        loadCombobox();
    }

    public void screanListProducts() {
        jTabbedPaneProduct.setSelectedIndex(0);
        listProducts();
    }

    public void loadCombobox() {
        List<Supplier> listS = supplierController.get("");
        jComboBoxSunpplierHistoryInput.removeAllItems();
        for (Supplier item : listS) {
            jComboBoxSunpplierHistoryInput.addItem(item);
        }

//        List<ReasonTaxes> listR = reasonTaxeController.get("");
//        jComboBoxReasonTaxeId.removeAllItems();
//        for (ReasonTaxes item : listR) {
//            jComboBoxReasonTaxeId.addItem(item);
//        }
    }

    public void loadListProducts(List<Product> list) {
        DefaultTableModel data = (DefaultTableModel) jTableProducts.getModel();
        data.setNumRows(0);
        for (Product c : list) {
            data.addRow(new Object[]{
                c.getId(),
                c.getType(),
                c.getCode(),
                //                c.getBarcode(),
                c.getDescription(),
                c.getPrice(),
                //                c.getPurchasePrice(),
                //                c.getStockTotal(),
                c.getTaxe(),
                c.getReasonTaxe(),
                //                c.getGroupId(),
                //                c.getSubGroupId(),
                //                c.getSupplier().getName(),
                c.getStatus(),
                c.getGroup()
            });
        }
    }

    public void listProducts() {
        List<Product> list = productController.get("");
        loadListProducts(list);
    }

    public void filterListProduct(String txt) {
//        ProductDao cDao = new ProductDao();
        List<Product> list = productController.filter(txt);
        loadListProducts(list);
    }

    public void loadListProductsInventory(List<Product> list) {
//        List<Product> list = productController.getProducts();
        DefaultTableModel data = (DefaultTableModel) jTableInventory.getModel();
        data.setNumRows(0);
        for (Product c : list) {
            data.addRow(new Object[]{
                c.getId(),
                c.getCode(),
                c.getBarcode(),
                c.getDescription(),
                c.getStockTotal(),
                c.getPrice(),
                c.getPurchasePrice(),
                c.getSupplier().getName(),
                c.getType()
            });
        }
    }

    public void listProductsInventory() {
//        List<Product> list = productController.getProducts();
        List<Product> list = productController.getProductsStock();
        loadListProductsInventory(list);
    }

    public void filterListProductInventory(String txt) {
//        ProductDao cDao = new ProductDao();
        List<Product> list = productController.filterProductStock(txt);
        loadListProductsInventory(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTabbedPaneProduct = new javax.swing.JTabbedPane();
        jPanelSearchSupplier = new javax.swing.JPanel();
        jTextFieldFilterNameTable = new javax.swing.JTextField();
        jButtonAlterSeleted = new javax.swing.JButton();
        jButtonDeleteSelectedTable = new javax.swing.JButton();
        jButtonOpenFormProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jButtonViewSeleted = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonGroups = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInventory = new javax.swing.JTable();
        jButtonAddProduct = new javax.swing.JButton();
        jButtonArmazem = new javax.swing.JButton();
        jButtonFormUpdateStock = new javax.swing.JButton();
        jTextFieldTxtSearchInventory = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonPurchaseProduct = new javax.swing.JButton();
        jButtonFormPurchase = new javax.swing.JButton();
        jComboBoxSunpplierHistoryInput = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jTabbedPaneProduct.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneProduct.setEnabled(false);
        jTabbedPaneProduct.setPreferredSize(new java.awt.Dimension(925, 620));

        jPanelSearchSupplier.setBackground(new java.awt.Color(204, 204, 255));

        jTextFieldFilterNameTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFilterNameTableActionPerformed(evt);
            }
        });
        jTextFieldFilterNameTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFilterNameTableKeyReleased(evt);
            }
        });

        jButtonAlterSeleted.setText("Editar");
        jButtonAlterSeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterSeletedActionPerformed(evt);
            }
        });

        jButtonDeleteSelectedTable.setText("Excluir");
        jButtonDeleteSelectedTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSelectedTableActionPerformed(evt);
            }
        });

        jButtonOpenFormProduct.setText("Novo Produto");
        jButtonOpenFormProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFormProductActionPerformed(evt);
            }
        });

        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Codigo", "Descrição", "Preço", "Imposto", "Razão do Imposto", "Status", "Grupo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProducts);

        jButtonViewSeleted.setText("Visualizar");
        jButtonViewSeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewSeletedActionPerformed(evt);
            }
        });

        jLabel2.setText("Procurar Produto");

        jButtonGroups.setText("Categoria");
        jButtonGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchSupplierLayout = new javax.swing.GroupLayout(jPanelSearchSupplier);
        jPanelSearchSupplier.setLayout(jPanelSearchSupplierLayout);
        jPanelSearchSupplierLayout.setHorizontalGroup(
            jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelSearchSupplierLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelSearchSupplierLayout.createSequentialGroup()
                        .addComponent(jTextFieldFilterNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(jButtonGroups)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpenFormProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonViewSeleted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterSeleted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteSelectedTable)))
                .addContainerGap())
        );
        jPanelSearchSupplierLayout.setVerticalGroup(
            jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchSupplierLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSearchSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFilterNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenFormProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterSeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteSelectedTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewSeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGroups))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSearchSupplierLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonGroups, jTextFieldFilterNameTable});

        jTabbedPaneProduct.addTab("Produtos e Serviços", jPanelSearchSupplier);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jTableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Codigo", "Codigo de Barra", "Produto", "Estoque", "Preço", "Preço Compra", "Fornecedor", "Armazem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableInventory);

        jButtonAddProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAddProduct.setText("Novo Produto");
        jButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductActionPerformed(evt);
            }
        });

        jButtonArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonArmazem.setText("Armazem");
        jButtonArmazem.setEnabled(false);
        jButtonArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArmazemActionPerformed(evt);
            }
        });

        jButtonFormUpdateStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFormUpdateStock.setText("Add Estoque");
        jButtonFormUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormUpdateStockActionPerformed(evt);
            }
        });

        jTextFieldTxtSearchInventory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTxtSearchInventoryKeyReleased(evt);
            }
        });

        jLabel3.setText("Pesquisar");

        jButtonPurchaseProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPurchaseProduct.setText("Comprar");
        jButtonPurchaseProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPurchaseProductActionPerformed(evt);
            }
        });

        jButtonFormPurchase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFormPurchase.setText("Entrada de Mercadoria");
        jButtonFormPurchase.setEnabled(false);
        jButtonFormPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormPurchaseActionPerformed(evt);
            }
        });

        jLabel5.setText("Selecione o Fornecedor");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Saida");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3))
                            .addComponent(jTextFieldTxtSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jComboBoxSunpplierHistoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 111, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonAddProduct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFormUpdateStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPurchaseProduct))
                            .addComponent(jButtonArmazem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jButtonFormPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButtonFormUpdateStock, jButtonPurchaseProduct});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFormPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTxtSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPurchaseProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSunpplierHistoryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButtonFormUpdateStock))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButtonAddProduct, jButtonArmazem, jButtonFormPurchase, jButtonFormUpdateStock, jButtonPurchaseProduct, jComboBoxSunpplierHistoryInput, jTextFieldTxtSearchInventory});

        jTabbedPaneProduct.addTab("Mercadoria", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jTabbedPaneProduct.addTab("Entrada", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jTabbedPaneProduct.addTab("Saida", jPanel3);

        jScrollPane4.setViewportView(jTabbedPaneProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTxtSearchInventoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTxtSearchInventoryKeyReleased
        // TODO add your handling code here:
        String txt = jTextFieldTxtSearchInventory.getText();
        if (!txt.isEmpty()) {
            filterListProductInventory(txt);
        } else {
            listProductsInventory();
        }
    }//GEN-LAST:event_jTextFieldTxtSearchInventoryKeyReleased

    private void jButtonFormUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormUpdateStockActionPerformed
        // TODO add your handling code here:
        new JDialogFormStock(null, true).setVisible(true);
        //        formStock.setVisible(true);

        //        int value = 0;
        //        try {
        //            value = (int) jTableInventory.getValueAt(jTableInventory.getSelectedRow(), 0);
        //            System.out.println("jTableUsers id:" + value);
        //        } catch (Exception e) {
        //            JOptionPane.showMessageDialog(null, "Selecione um Products na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        //        } finally {
        ////            System.out.println("jTableUsers id:" + value);
        //            if (value > 0) {
        //                JDialogFormStock formStock = new JDialogFormStock(null, true);
        //                formStock.setProduct(value);
        //                formStock.setVisible(true);
        //                Boolean resp = formStock.getResponse();
        //                if (resp == true) {
        //                    JOptionPane.showMessageDialog(null, "Estoque do Product atualizado com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        listProducts();
        listProductsInventory();
        //                }
        //            }
        //        }
    }//GEN-LAST:event_jButtonFormUpdateStockActionPerformed

    private void jButtonArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArmazemActionPerformed
        // TODO add your handling code here:
        new JDialogWarehouse(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonArmazemActionPerformed

    private void jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductActionPerformed
        // TODO add your handling code here:
        JDialogFormProduct formProd = new JDialogFormProduct(null, true);
        //        formProd.setFormProduct(prod);
        formProd.setVisible(true);
        Boolean resp = formProd.getResponse();
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Products salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            listProducts();
            listProductsInventory();
        }
    }//GEN-LAST:event_jButtonAddProductActionPerformed

    private void jButtonFormPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormPurchaseActionPerformed
        // TODO add your handling code here:
        JDialogFormPurchase formPurchase = new JDialogFormPurchase(null, true);
        formPurchase.setVisible(true);
    }//GEN-LAST:event_jButtonFormPurchaseActionPerformed

    private void jButtonViewSeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewSeletedActionPerformed
        // TODO add your handling code here:

        int id = 0;
        try {
            id = (int) jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0);
//            System.out.println("jTableUsers id:" + value);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um Products na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {

//            int id = Integer.parseInt(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0).toString());
            if (id > 0) {
                Product prod = productController.getId(id);
                JOptionPane.showMessageDialog(null, "Produto :" + prod.getDescription() + "\n Codigo de barra:" + prod.getBarcode() + "\n Preço:" + prod.getPrice() + "\n Status:" + prod.getStatus());

//                JDialogFormProduct formProd = new JDialogFormProduct(null, true);
//                formProd.setProduct(value);
//                formProd.setVisible(true);
//                Boolean resp = formProd.getResponse();
//                if (resp == true) {
//                    JOptionPane.showMessageDialog(null, "FormProduct salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
//                    listProducts();
//                }
            }
        }
    }//GEN-LAST:event_jButtonViewSeletedActionPerformed

    private void jTableProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductsMouseClicked
        // TODO add your handling code here:
        //        jTabbedPaneProduct.setSelectedIndex(1);
        //        jTextFieldId.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0).toString());
        //        jComboBoxType.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 1));
        //        jTextFieldCode.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 2).toString());
        //        jTextFieldBarCode.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 3).toString());
        //        jTextFieldDescription.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 4).toString());
        //        jTextFieldPrice.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 5).toString());
        //        jTextFieldPurchasePrice.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 6).toString());
        //        jTextFieldStockTotal.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 7).toString());
        //        jComboBoxTaxeId.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 8));
        //        jComboBoxReasonTaxeId.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 9));
        //        jComboBoxReasonTaxeId.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 10));
        //        jComboBoxSupplier.setSelectedIndex((int) jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 11));
        //        jComboBoxGroup.setSelectedIndex((int) jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 12));
    }//GEN-LAST:event_jTableProductsMouseClicked

    private void jButtonOpenFormProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFormProductActionPerformed
        // TODO add your handling code here:
        JDialogFormProduct formProd = new JDialogFormProduct(null, true);
        //        formProd.setFormProduct(prod);
        formProd.setVisible(true);
        Boolean resp = formProd.getResponse();
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Products salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            listProducts();
        }

        //        jTabbedPaneProduct.setSelectedIndex(1);
        //        Utilities helpUtil = new Utilities();
        //        helpUtil.clearScreen(jPanelFormSupplier);
    }//GEN-LAST:event_jButtonOpenFormProductActionPerformed

    private void jButtonDeleteSelectedTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSelectedTableActionPerformed
        // TODO add your handling code here:
        int id = 0;
        try {
//             int id = Integer.parseInt(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0).toString());
            id = (int) jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0);
            System.out.println("jTableProducts id:" + id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um Products na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {

            Product prod = productController.getId(id);
            //        JOptionPane.showMessageDialog(null, "Cliente :" + client.getName());
            int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Deletar," + prod.getDescription() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (sair == JOptionPane.YES_OPTION) {
                if (productController.deleteId(id)) {
                    JOptionPane.showMessageDialog(null, "products excluido com Sucesso!!");
                    listProducts();
                }
            }
        }
    }//GEN-LAST:event_jButtonDeleteSelectedTableActionPerformed

    private void jButtonAlterSeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterSeletedActionPerformed
        // TODO add your handling code here:
        //        jTabbedPaneProduct.setSelectedIndex(1);
        //        jTextFieldId.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0).toString());
        //        jComboBoxType.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 1));
        //        jTextFieldCode.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 2).toString());
        //        jTextFieldBarCode.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 3).toString());
        //        jTextFieldDescription.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 4).toString());
        //        jTextFieldPrice.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 5).toString());
        //        jTextFieldPurchasePrice.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 6).toString());
        //        jTextFieldStockTotal.setText(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 7).toString());
        //        jComboBoxTaxeId.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 8));
        //        jComboBoxReasonTaxeId.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 9));
        //        jComboBoxReasonTaxeId.setSelectedItem(jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 10));
        //        jComboBoxSupplier.setSelectedIndex((int) jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 11));

        //        JDialogFormProduct formProd = new JDialogFormProduct(null, true);
        //        Product prod = productController.getId(if);
        //        formProd.setFormProduct(prod);
        //        formProd.setVisible(true);
        //        Boolean resp = formProd.getResponse();
        //        if (resp == true) {
        //            JOptionPane.showMessageDialog(null, "Products salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        //            listProducts();
        //        }
        int value = 0;
        try {
            value = (int) jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0);
            System.out.println("jTableUsers id:" + value);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um Products na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {
            //            System.out.println("jTableUsers id:" + value);
            if (value > 0) {
                JDialogFormProduct formProd = new JDialogFormProduct(null, true);
                formProd.setProduct(value);
                formProd.setVisible(true);
                Boolean resp = formProd.getResponse();
                if (resp == true) {
                    JOptionPane.showMessageDialog(null, "FormProduct salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    listProducts();
                }
            }
        }
    }//GEN-LAST:event_jButtonAlterSeletedActionPerformed

    private void jTextFieldFilterNameTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterNameTableKeyReleased
        // TODO add your handling code here:
        String txt = jTextFieldFilterNameTable.getText();
        if (!txt.isEmpty()) {
            filterListProduct(txt);
        } else {
            listProducts();
        }
    }//GEN-LAST:event_jTextFieldFilterNameTableKeyReleased

    private void jTextFieldFilterNameTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFilterNameTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFilterNameTableActionPerformed

    private void jButtonGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupsActionPerformed
        // TODO add your handling code here:
        JDialogCategoryProduct jGroup = new JDialogCategoryProduct(null, true);
        jGroup.setVisible(true);
    }//GEN-LAST:event_jButtonGroupsActionPerformed

    private void jButtonPurchaseProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPurchaseProductActionPerformed
        // TODO add your handling code here:
        int value = 0;
        try {
            value = (int) jTableInventory.getValueAt(jTableInventory.getSelectedRow(), 0);
//            System.out.println("jTableUsers id:" + value);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um Products na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {
            //            System.out.println("jTableUsers id:" + value);
            if (value > 0) {
                JDialogPurchaseProduct jPurchaseProd = new JDialogPurchaseProduct(null, true);
                jPurchaseProd.setProduct(value);
                jPurchaseProd.setVisible(true);
                Boolean resp = jPurchaseProd.getResponse();
                if (resp == true) {
                    JOptionPane.showMessageDialog(null, "Compra efetuada com com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    listProducts();
                }
            }
        }
    }//GEN-LAST:event_jButtonPurchaseProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonAlterSeleted;
    private javax.swing.JButton jButtonArmazem;
    private javax.swing.JButton jButtonDeleteSelectedTable;
    private javax.swing.JButton jButtonFormPurchase;
    private javax.swing.JButton jButtonFormUpdateStock;
    private javax.swing.JButton jButtonGroups;
    private javax.swing.JButton jButtonOpenFormProduct;
    private javax.swing.JButton jButtonPurchaseProduct;
    private javax.swing.JButton jButtonViewSeleted;
    private javax.swing.JComboBox jComboBoxSunpplierHistoryInput;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSearchSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPaneProduct;
    private javax.swing.JTable jTableInventory;
    private javax.swing.JTable jTableProducts;
    private javax.swing.JTextField jTextFieldFilterNameTable;
    private javax.swing.JTextField jTextFieldTxtSearchInventory;
    // End of variables declaration//GEN-END:variables
}
