/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.okutonda.okudpdv.views.login;

import com.formdev.flatlaf.FlatLightLaf;
import com.okutonda.okudpdv.controllers.OptionController;
import com.okutonda.okudpdv.controllers.UserController;
import com.okutonda.okudpdv.jdbc.ConnectionDatabase;
import com.okutonda.okudpdv.models.User;
import com.okutonda.okudpdv.utilities.CompanySession;
import com.okutonda.okudpdv.views.suport.JDialogSuport;
import com.okutonda.okudpdv.views.ScreenMain;
import com.okutonda.okudpdv.views.install.JDialogInstallInsertUser;
import com.okutonda.okudpdv.views.pdv.ScreenPdv;
import com.okutonda.okudpdv.views.install.ScreenInstall;
import com.okutonda.okudpdv.views.suport.JDialogAbout;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author kenny
 */
public class ScreenLogin extends javax.swing.JFrame {

    UserController userController = new UserController();
    CompanySession companySession = CompanySession.getInstance();
    OptionController optionController = new OptionController();
    private final Connection conn;

    /**
     * Creates new form ScreenLogin
     */
    public ScreenLogin() {
        initComponents();
//        this.setExtendedState(ScreenLogin.MAXIMIZED_BOTH);
        this.conn = ConnectionDatabase.getConnect();
//        this.conn = new ConnectDB().connect();
        if (this.conn != null) {
            jLabelStatusBdConect.setText("Conectado");
            loadDataCompany();
//            loadDataCompany();
        } else {
            jLabelStatusBdConect.setText("Desconectado");
        }
        
        jLabelNameCompany.setText(companySession.getName());

        List<User> response = userController.get("");

        if (response == null || response.isEmpty()) {
            JDialogInstallInsertUser jdInstallUser = new JDialogInstallInsertUser(this, true);
//                    jdInstallUser.setOrder(order);
            jdInstallUser.setVisible(true);
        }

//        AdminRoot root = new AdminRoot();
//        if (!Boolean.parseBoolean(root.getStatusSoftware())) {
//            JOptionPane.showMessageDialog(
//                    null,
//                    "O sistema está inativo",
//                    "Atenção",
//                    JOptionPane.ERROR_MESSAGE
//            );
//            new JDialogSuport(this, rootPaneCheckingEnabled).setVisible(true);
//        }
    }

    public void loadDataCompany() {
//        System.out.println("key:"+optionController.getValueOptions("companyKeyLicence"));
        companySession.setName(optionController.getValueOptions("companyName"));
        companySession.setNif(optionController.getValueOptions("companyNif"));
        companySession.setAddress(optionController.getValueOptions("companyAddress"));
        companySession.setPhone(optionController.getValueOptions("companyPhone"));
        companySession.setEntity(optionController.getValueOptions("entity"));
        companySession.setKeyLicence(optionController.getValueOptions("companyKeyLicence"));
    }

    public void login(String email, String password) {

        User response = userController.login(email, password);
        if (response != null) {
            if (response.getStatus() == 1) {
                if (response.getProfile().equals("seller")) {
                    ScreenPdv pdv = new ScreenPdv();
                    this.dispose();
                    pdv.setVisible(true);
                } else {
                    ScreenMain main = new ScreenMain();
                    this.dispose();
                    main.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario desativado!!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Dados Invalidos!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonSuport = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();
        jButtonInstall = new javax.swing.JButton();
        jLabelStatusBdConect = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonLogin = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelNameCompany = new javax.swing.JLabel();
        jButtonCloseScreen = new javax.swing.JButton();
        jLabelImgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSuport.setText("Suport");
        jButtonSuport.setContentAreaFilled(false);
        jButtonSuport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuportActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSuport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 70, -1));

        jButtonAbout.setText("About");
        jButtonAbout.setContentAreaFilled(false);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 70, -1));

        jButtonInstall.setText("instalar");
        jButtonInstall.setContentAreaFilled(false);
        jButtonInstall.setEnabled(false);
        jButtonInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstallActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonInstall, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 70, -1));

        jLabelStatusBdConect.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabelStatusBdConect.setText("Desconectado");
        jPanel3.add(jLabelStatusBdConect, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 80, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("Entrada");

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 102));
        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Entrar");
        jButtonLogin.setToolTipText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jPasswordFieldPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordFieldPassword.setForeground(new java.awt.Color(0, 0, 102));
        jPasswordFieldPassword.setText("12345678");
        jPasswordFieldPassword.setToolTipText("Senha");
        jPasswordFieldPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordFieldPassword.setCaretColor(new java.awt.Color(0, 0, 102));
        jPasswordFieldPassword.setFocusable(false);
        jPasswordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Senha:");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 102));
        jTextFieldEmail.setText("admin@admin.com");
        jTextFieldEmail.setToolTipText("Email");
        jTextFieldEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldEmail.setCaretColor(new java.awt.Color(0, 0, 102));
        jTextFieldEmail.setFocusable(false);
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Email:");

        jLabelNameCompany.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNameCompany.setForeground(new java.awt.Color(0, 0, 102));
        jLabelNameCompany.setText("ENTRAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNameCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordFieldPassword, jTextFieldEmail});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelNameCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 380, 300));

        jButtonCloseScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close.png"))); // NOI18N
        jButtonCloseScreen.setBorderPainted(false);
        jButtonCloseScreen.setContentAreaFilled(false);
        jButtonCloseScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCloseScreen.setFocusable(false);
        jButtonCloseScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseScreenActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCloseScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 30));

        jLabelImgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img_1.jpg"))); // NOI18N
        jPanel3.add(jLabelImgFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed

        String email, password;
        email = jTextFieldEmail.getText();
        password = new String(jPasswordFieldPassword.getPassword());
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Prencha o formulario para continuar...", "Atenção", JOptionPane.ERROR_MESSAGE);
        } else {

            this.login(email, password);

//            User response = userController.login(email, password);
//            if (response != null) {
//                if (response.getStatus() == 1) {
//                    if (response.getProfile().equals("seller")) {
//                        ScreenPdv pdv = new ScreenPdv();
//                        this.dispose();
//                        pdv.setVisible(true);
//                    } else {
//                        ScreenMain main = new ScreenMain();
//                        this.dispose();
//                        main.setVisible(true);
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(null, "Usuario desativado!!");
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Dados Invalidos!!");
//            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordActionPerformed

    private void jButtonSuportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuportActionPerformed
        // TODO add your handling code here:
        new JDialogSuport(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButtonSuportActionPerformed

    private void jButtonCloseScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseScreenActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Fechar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonCloseScreenActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
        // TODO add your handling code here:
        new JDialogAbout(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButtonAboutActionPerformed

    private void jButtonInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstallActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ScreenInstall().setVisible(true);
    }//GEN-LAST:event_jButtonInstallActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        loadDataCompany();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ScreenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonCloseScreen;
    private javax.swing.JButton jButtonInstall;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSuport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImgFundo;
    private javax.swing.JLabel jLabelNameCompany;
    public javax.swing.JLabel jLabelStatusBdConect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
