/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.okutonda.okudpdv.views.pdv;

import com.okutonda.okudpdv.controllers.PurchaseController;
import com.okutonda.okudpdv.data.entities.Product;
import com.okutonda.okudpdv.data.entities.Purchase;
import com.okutonda.okudpdv.data.entities.PurchaseItem;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rog
 */
public class JDialogDetailPurchase extends javax.swing.JDialog {

    private Purchase purchase;
    private PurchaseController purchasesController = new PurchaseController();

    /**
     * Creates new form JDialogDetailPurchase
     */
    public JDialogDetailPurchase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setOrder(int id) {
        System.out.println("id purchase view: " + id);
        this.purchase = this.purchasesController.findById(id);
        preencherCampos(); // ✅ atualiza os labels e tabela
    }

    private void preencherCampos() {
        if (purchase == null) {
            JOptionPane.showMessageDialog(this, "Nenhuma compra selecionada.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 🧾 Dados principais
        jLabelNumber.setText("Nº: " + purchase.getInvoiceNumber());
        jLabelData.setText("Data: " + new java.text.SimpleDateFormat("dd/MM/yyyy").format(purchase.getDataCompra()));
        jLabelTotal.setText("Total: " + purchase.getTotal() + " AOA");

        // 🧍‍♂️ Fornecedor (comprado de)
        if (purchase.getSupplier() != null) {
            jLabelDadosVendedor.setText(
                    "<html><b>Fornecedor:</b> " + purchase.getSupplier().getName() + "</html>"
            );
        } else {
            jLabelDadosVendedor.setText("<html><b>Fornecedor:</b> - </html>");
        }

        // 👤 Usuário que registou
        if (purchase.getUser() != null) {
            jLabelDadosComprador.setText(
                    "<html><b>Registado por:</b> " + purchase.getUser().getName() + "</html>"
            );
        } else {
            jLabelDadosComprador.setText("<html><b>Registado por:</b> - </html>");
        }

        // 💰 Pagamentos
        BigDecimal totalPago = purchase.getTotal_pago() != null ? purchase.getTotal_pago() : BigDecimal.ZERO;
        BigDecimal saldo = purchase.getTotal().subtract(totalPago);
        jLabelDadosPagamentos.setText(
                "<html><b>Total Pago:</b> " + totalPago + " AOA<br>"
                + "<b>Saldo:</b> " + saldo + " AOA<br>"
                + "<b>Status:</b> " + purchase.getStatus() + "</html>"
        );

        // 🧾 Tabela de produtos
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Produto");
        model.addColumn("Quantidade");
        model.addColumn("Preço Custo");
        model.addColumn("IVA (%)");
        model.addColumn("Subtotal");
        model.addColumn("Total c/ IVA"); // nova coluna

        if (purchase.getItems() != null) {
            for (PurchaseItem item : purchase.getItems()) {
                Product produto = item.getProduct();

                // Cálculo seguro do subtotal
                BigDecimal subtotal = item.getSubtotal() != null
                        ? item.getSubtotal()
                        : item.getPrecoCusto().multiply(BigDecimal.valueOf(item.getQuantidade()));

                BigDecimal ivaPercent = item.getIva() != null ? item.getIva() : BigDecimal.ZERO;
                BigDecimal valorIva = subtotal.multiply(ivaPercent.divide(BigDecimal.valueOf(100)));
                BigDecimal totalComIva = subtotal.add(valorIva);

                model.addRow(new Object[]{
                    (produto != null ? produto.getDescription(): "—"),
                    item.getQuantidade(),
                    item.getPrecoCusto(),
                    ivaPercent + " %",
                    subtotal,
                    totalComIva
                });
            }
        }

        jTableTabelaProdutos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDadosPagamentos = new javax.swing.JLabel();
        jLabelDadosComprador = new javax.swing.JLabel();
        jLabelDadosVendedor = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableTabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTabelaProdutos);

        jLabel1.setText("Produtos comprados");

        jLabelDadosPagamentos.setText("Pagamentos");

        jLabelDadosComprador.setText("Comprador");

        jLabelDadosVendedor.setText("Dados do cliente");

        jLabelTotal.setText("Total");

        jLabelData.setText("Datas");

        jLabelNumber.setText("Numero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDadosPagamentos)
                    .addComponent(jLabelData)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelDadosVendedor)
                    .addComponent(jLabelDadosComprador)
                    .addComponent(jLabelNumber))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelData)
                .addGap(18, 18, 18)
                .addComponent(jLabelDadosVendedor)
                .addGap(22, 22, 22)
                .addComponent(jLabelDadosComprador)
                .addGap(27, 27, 27)
                .addComponent(jLabelTotal)
                .addGap(27, 27, 27)
                .addComponent(jLabelDadosPagamentos)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setText("Detalhes da compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(735, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogDetailPurchase dialog = new JDialogDetailPurchase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDadosComprador;
    private javax.swing.JLabel jLabelDadosPagamentos;
    private javax.swing.JLabel jLabelDadosVendedor;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
