/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.okutonda.okudpdv.views.users;

import com.okutonda.okudpdv.controllers.UserController;
import com.okutonda.okudpdv.models.User;
import com.okutonda.okudpdv.utilities.UserSession;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kenny
 */
public final class JPanelUser extends javax.swing.JPanel {

    UserController userController = new UserController();
//    CountryController countryController = new CountryController();
    UserSession session;

    public void listUsers() {
        List<User> list = userController.get("");
        DefaultTableModel data = (DefaultTableModel) jTableUsers.getModel();
        data.setNumRows(0);
        for (User c : list) {
            data.addRow(new Object[]{
                c.getId(),
                c.getNif(),
                c.getName(),
                c.getBirthdate(),
                c.getEmail(),
                c.getPhone(),
                c.getProfile(),
//                c.getCountry(),
//                c.getCity(),
                c.getAddress(),
                c.getStatus()
            });
        }
    }

    public void filterListUsers(String txt) {
        List<User> list = userController.filter(txt);
        DefaultTableModel data = (DefaultTableModel) jTableUsers.getModel();
        data.setNumRows(0);
        for (User c : list) {
            data.addRow(new Object[]{
                c.getId(),
                c.getNif(),
                c.getName(),
                c.getEmail(),
                c.getPhone(),
                c.getProfile(),
//                c.getCountry(),
//                c.getCity(),
                c.getBirthdate(),
                c.getAddress(),
                c.getStatus()
            });
        }
    }

    public void roles() {
        switch (session.getUser().getProfile()) {
            case "admin":
                break;
            case "user":
                this.jButtonOpenFormUser.setEnabled(false);
                this.jButtonAlterSeleted.setEnabled(false);
                this.jButtonDeleteSelected.setEnabled(false);
                break;
            case "seller":
                this.jButtonOpenFormUser.setEnabled(false);
                this.jButtonAlterSeleted.setEnabled(false);
                this.jButtonDeleteSelected.setEnabled(false);
                break;
            case "manager":
                this.jButtonOpenFormUser.setEnabled(false);
                this.jButtonAlterSeleted.setEnabled(false);
                this.jButtonDeleteSelected.setEnabled(false);
                break;
            default:
                break;
        }
    }

    /**
     * Creates new form NewJPanelUser
     */
    public JPanelUser() {
        initComponents();
        session = UserSession.getInstance();
        listUsers();
    }

    public void screanListUser() {
        jTabbedPaneUsers.setSelectedIndex(0);
        listUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTabbedPaneUsers = new javax.swing.JTabbedPane();
        jPanelSearchUser = new javax.swing.JPanel();
        jButtonFilterNameTable = new javax.swing.JButton();
        jTextFieldFilterNameTable = new javax.swing.JTextField();
        jButtonAlterSeleted = new javax.swing.JButton();
        jButtonDeleteSelected = new javax.swing.JButton();
        jButtonOpenFormUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jButtonViewSelected = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTabbedPaneUsers.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneUsers.setEnabled(false);

        jPanelSearchUser.setBackground(new java.awt.Color(204, 204, 255));

        jButtonFilterNameTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        jButtonFilterNameTable.setText("Pesquisar");
        jButtonFilterNameTable.setContentAreaFilled(false);
        jButtonFilterNameTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFilterNameTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterNameTableActionPerformed(evt);
            }
        });

        jTextFieldFilterNameTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFilterNameTableKeyReleased(evt);
            }
        });

        jButtonAlterSeleted.setBackground(new java.awt.Color(255, 255, 153));
        jButtonAlterSeleted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit Pencil.png"))); // NOI18N
        jButtonAlterSeleted.setText("Alterar");
        jButtonAlterSeleted.setToolTipText("Editar Usuario");
        jButtonAlterSeleted.setContentAreaFilled(false);
        jButtonAlterSeleted.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterSeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterSeletedActionPerformed(evt);
            }
        });

        jButtonDeleteSelected.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDeleteSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash Can.png"))); // NOI18N
        jButtonDeleteSelected.setText("Excluir");
        jButtonDeleteSelected.setToolTipText("Apagar usuario");
        jButtonDeleteSelected.setContentAreaFilled(false);
        jButtonDeleteSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSelectedActionPerformed(evt);
            }
        });

        jButtonOpenFormUser.setBackground(new java.awt.Color(153, 153, 255));
        jButtonOpenFormUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Plus.png"))); // NOI18N
        jButtonOpenFormUser.setText("Adicionar");
        jButtonOpenFormUser.setContentAreaFilled(false);
        jButtonOpenFormUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOpenFormUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenFormUserActionPerformed(evt);
            }
        });

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIF", "Nome", "birthdate", "Email", "Telefone", "profile", "Endereço", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsers);

        jButtonViewSelected.setBackground(new java.awt.Color(153, 255, 153));
        jButtonViewSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Binoculars.png"))); // NOI18N
        jButtonViewSelected.setText("Ver");
        jButtonViewSelected.setToolTipText("Ver os dados");
        jButtonViewSelected.setContentAreaFilled(false);
        jButtonViewSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonViewSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchUserLayout = new javax.swing.GroupLayout(jPanelSearchUser);
        jPanelSearchUser.setLayout(jPanelSearchUserLayout);
        jPanelSearchUserLayout.setHorizontalGroup(
            jPanelSearchUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelSearchUserLayout.createSequentialGroup()
                        .addComponent(jTextFieldFilterNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFilterNameTable)
                        .addGap(78, 78, 78)
                        .addComponent(jButtonOpenFormUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonViewSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterSeleted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteSelected)
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSearchUserLayout.setVerticalGroup(
            jPanelSearchUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchUserLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelSearchUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFilterNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFilterNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenFormUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterSeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jTabbedPaneUsers.addTab("Usuarios", jPanelSearchUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        jTabbedPaneUsers.addTab("Regras", jPanel1);

        jScrollPane2.setViewportView(jTabbedPaneUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilterNameTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterNameTableActionPerformed
        // TODO add your handling code here:
        String txt = jTextFieldFilterNameTable.getText();
        if (!txt.isEmpty()) {
            filterListUsers(txt);
        } else {
            listUsers();
        }
    }//GEN-LAST:event_jButtonFilterNameTableActionPerformed

    private void jTextFieldFilterNameTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterNameTableKeyReleased
        // TODO add your handling code here:
        String txt = jTextFieldFilterNameTable.getText();
        if (!txt.isEmpty()) {
            filterListUsers(txt);
        } else {
            listUsers();
        }
    }//GEN-LAST:event_jTextFieldFilterNameTableKeyReleased

    private void jButtonAlterSeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterSeletedActionPerformed
        // TODO add your handling code here:
        int value = 0;
        try {
            value = (int) jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um usuario na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (value > 0) {
                JDialogFormUser formUser = new JDialogFormUser(null, true);
                formUser.setUser(value);
                formUser.setVisible(true);
                Boolean resp = formUser.getResponse();
                if (resp == true) {
                    JOptionPane.showMessageDialog(null, "Usuario salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    listUsers();
                }
            }
        }
    }//GEN-LAST:event_jButtonAlterSeletedActionPerformed

    private void jButtonDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSelectedActionPerformed
        // TODO add your handling code here:
//        int id = Integer.parseInt(jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 0).toString());
//        User user = userController.getId(id);
//        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar," + user.getName() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (sair == JOptionPane.YES_OPTION) {
//            if (userController.deleteId(id)) {
//                JOptionPane.showMessageDialog(null, "Usuario excluido com Sucesso!!");
//                listUsers();
//            }
//        }
        int value = 0;
        try {
            value = (int) jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 0);
            System.out.println("jTableUsers id:" + value);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um usuario na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {
            System.out.println("jTableUsers id:" + value);
            if (value > 0) {
                User userD = userController.getId(value);
                int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar," + userD.getName() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (sair == JOptionPane.YES_OPTION) {
                    if (userController.deleteId(userD.getId())) {
                        JOptionPane.showMessageDialog(null, "Usuario excluido com Sucesso!!");
                        listUsers();
                    }
                }
//                JDialogFormUser formUser = new JDialogFormUser(null, true);
//                formUser.setUser(value);
//                formUser.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonDeleteSelectedActionPerformed

    private void jButtonOpenFormUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFormUserActionPerformed
        // TODO add your handling code here:
        JDialogFormUser formUser = new JDialogFormUser(null, true);
        formUser.setVisible(true);
        Boolean resp = formUser.getResponse();
        if (resp == true) {
            JOptionPane.showMessageDialog(null, "Usuario salvo com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            listUsers();
        }
    }//GEN-LAST:event_jButtonOpenFormUserActionPerformed

    private void jTableUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableUsersMouseClicked

    private void jButtonViewSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewSelectedActionPerformed
        // TODO add your handling code here:
        int value = 0;
        try {
            value = (int) jTableUsers.getValueAt(jTableUsers.getSelectedRow(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um usuario na tabela!!", "Atencao", JOptionPane.ERROR_MESSAGE);
        } finally {
            if (value > 0) {
                User user = userController.getId(value);
                JOptionPane.showMessageDialog(null, "Usuario :" + user.getName() + "\n Perfil:" + user.getProfile() + "\n Email:" + user.getEmail() + "\n Endereço:" + user.getAddress());
//                JDialogFormUser formUser = new JDialogFormUser(null, true);
//                formUser.setUser(value);
//                formUser.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonViewSelectedActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAlterSeleted;
    public javax.swing.JButton jButtonDeleteSelected;
    private javax.swing.JButton jButtonFilterNameTable;
    public javax.swing.JButton jButtonOpenFormUser;
    private javax.swing.JButton jButtonViewSelected;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSearchUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneUsers;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextFieldFilterNameTable;
    // End of variables declaration//GEN-END:variables
}
