/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.okutonda.okudpdv.views.purchases;

import com.okutonda.okudpdv.data.entities.Purchase;

/**
 *
 * @author hr
 */
public class JDialogPayPurchase extends javax.swing.JDialog {

    private Purchase compra;
    private boolean pagamentoProcessado = false;

    /**
     * Creates new form JDialogPayPurchase
     */
    public JDialogPayPurchase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

//        carregarDadosCompra();
    }
//
//    /**
//     * Define a compra a ser paga
//     */
//    public void setCompra(Purchase compra) {
//        this.compra = compra;
//        carregarDadosCompra();
//    }
//
//    /**
//     * Retorna se o pagamento foi processado
//     */
//    public boolean isPagamentoProcessado() {
//        return pagamentoProcessado;
//    }
//
//    /**
//     * Carrega os dados da compra na interface
//     */
//    private void carregarDadosCompra() {
//        if (compra != null) {
//            // Preenche os campos com os dados da compra
//            jTextFieldCompraId.setText(String.valueOf(compra.getId()));
//            jTextFieldNumeroFatura.setText(compra.getInvoiceNumber());
//            jTextFieldFornecedor.setText(compra.getSupplier().getName());
//            jTextFieldTotal.setText(String.valueOf(compra.getTotalAmount()));
//            jTextFieldData.setText(compra.getPurchaseDate().toString());
//
//            // Aqui você pode adicionar mais campos conforme necessário
//        }
//    }
//
//    /**
//     * Processa o pagamento da compra
//     */
//    private void processarPagamento() {
//        try {
//            // Aqui você implementa a lógica de pagamento
//            // Exemplo: integração com gateway de pagamento, registro no banco, etc.
//
//            // Simulação de processamento bem-sucedido
//            boolean pagamentoSucesso = true; // Substitua pela lógica real
//
//            if (pagamentoSucesso) {
//                // Atualiza o status da compra para PAGA
//                PurchaseController purchaseController = new PurchaseController();
//                boolean atualizado = purchaseController.atualizarStatusCompra(compra.getId(), "PAGA");
//
//                if (atualizado) {
//                    pagamentoProcessado = true;
//                    JOptionPane.showMessageDialog(this,
//                            "Pagamento processado com sucesso!",
//                            "Sucesso",
//                            JOptionPane.INFORMATION_MESSAGE);
//                    this.dispose();
//                } else {
//                    JOptionPane.showMessageDialog(this,
//                            "Erro ao atualizar status da compra!",
//                            "Erro",
//                            JOptionPane.ERROR_MESSAGE);
//                }
//            } else {
//                JOptionPane.showMessageDialog(this,
//                        "Falha no processamento do pagamento!",
//                        "Erro",
//                        JOptionPane.ERROR_MESSAGE);
//            }
//
//        } catch (Exception e) {
//            System.err.println("❌ Erro ao processar pagamento: " + e.getMessage());
//            JOptionPane.showMessageDialog(this,
//                    "Erro ao processar pagamento: " + e.getMessage(),
//                    "Erro",
//                    JOptionPane.ERROR_MESSAGE);
//        }
//    }
//
//    // Método chamado pelo botão de confirmar pagamento
//    private void jButtonConfirmarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {
//        processarPagamento();
//    }
//
//    // Método chamado pelo botão de cancelar
//    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {
//        pagamentoProcessado = false;
//        this.dispose();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPayPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPayPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPayPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPayPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPayPurchase dialog = new JDialogPayPurchase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
