/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.okutonda.okudpdv.views.install;

import com.okutonda.okudpdv.controllers.Install;
import com.okutonda.okudpdv.controllers.OptionController;
import com.okutonda.okudpdv.controllers.UserController;
import com.okutonda.okudpdv.data.entities.Options;
import com.okutonda.okudpdv.views.login.ScreenLogin;
import com.okutonda.okudpdv.data.entities.User;
import com.okutonda.okudpdv.views.suport.JDialogSuport;
import com.okutonda.okudpdv.views.suport.JDialogAbout;
import javax.swing.JOptionPane;

/**
 *
 * @author kenny
 */
public final class ScreenInstall extends javax.swing.JFrame {

    OptionController optionController;
    UserController userController = new UserController();
    Install install;

    /**
     * Creates new form JFrameInstall
     */
    public ScreenInstall() {
        initComponents();

        optionController = new OptionController();
        install = new Install();

    }

    public void messageAlert() {
        String txt = "Antes de proseguir com a instalaco tenha certeza";
        txt += " que nao exista qualquer \n instalação anterior, para envitar ";
        txt += "Perdas de dados, pois essa instacao pode subscrever o \n";
        txt += "Banco de dados \n";
        txt += "\n ********************************************* \n";

        txt += "1 - Caso ja tenha uma instalacao anterior: \n ";
        txt += "1.1 Verificar a conexao com o Banco de dados.\n ";
        txt += "1.2 Verifica se a licença esta no prazo.\n ";
        txt += "1.3 Entrar em contacto com a nossa equipa.\n ";
        txt += "\n ";
        txt += "2 - Nao tenho instalacao anterior: \n ";
        txt += "2.1 - Fica avontade para continuar a instacao \n ";
//        txt += "Clique em OK e depois em Login que sera redirecionado para a tela de login \n ";

        txt += "\n ********************************************* \n";
        txt += "Para mais informacao:";
        txt += "\n Leia a documentação ";
        txt += "\n Ou entre em contacto com a nossa equipa.";
        txt += "\n Nosso site: www.okutonda.com";
        txt += "\n ********************************************* \n";

        jTextAreaAlert.setText(txt);
//        JOptionPane.showMessageDialog(null, txt, "ATT", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonInstall = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonSuportInstall = new javax.swing.JButton();
        jButtonContato = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlert = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jButtonInstall.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInstall.setText("Instalar");
        jButtonInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstallActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Aviso");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tela de Instalação");

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Para mais informação clique");

        jButtonSuportInstall.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSuportInstall.setText("Suport");
        jButtonSuportInstall.setContentAreaFilled(false);
        jButtonSuportInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuportInstallActionPerformed(evt);
            }
        });

        jButtonContato.setBackground(new java.awt.Color(204, 204, 204));
        jButtonContato.setText("Contato");
        jButtonContato.setContentAreaFilled(false);
        jButtonContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContatoActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("ou");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton1.setText("Login");
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextAreaAlert.setColumns(20);
        jTextAreaAlert.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAlert);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSuportInstall)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonContato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonInstall, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(jButtonInstall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButtonSuportInstall)
                    .addComponent(jButtonContato)
                    .addComponent(jLabel14))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(699, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSuportInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuportInstallActionPerformed
        // TODO add your handling code here:
        new JDialogSuport(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButtonSuportInstallActionPerformed

    private void jButtonContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContatoActionPerformed
        // TODO add your handling code here:
//        ScreenContact conatct = new ScreenContact();
//        conatct.setVisible(true);
        new JDialogAbout(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButtonContatoActionPerformed

    private void jButtonInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstallActionPerformed
        // TODO add your handling code here:

//        int sair = JOptionPane.showConfirmDialog(null, "Clique sim para instalar.", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (sair == JOptionPane.YES_OPTION) {
//            int status = install.installDatabase();
//            if (status == 1) {
////                    insertUser(cModel);
////                    inserDataCompany();
//                JOptionPane.showMessageDialog(null, "Instalacao do banco de Dados...");
//
//                JDialogInstallInsertUser jdInstallUser = new JDialogInstallInsertUser(this, true);
////                    jdInstallUser.setOrder(order);
//                jdInstallUser.setVisible(true);
//
//                Boolean respo = jdInstallUser.getResponse();
//
//                ScreenLogin frame = new ScreenLogin();
//                this.dispose();
//                frame.setVisible(true);
//            } else if (status == 0) {
//                JOptionPane.showMessageDialog(null, "Erro ao instalar Banco de Dados!!", "Atenºão", JOptionPane.ERROR_MESSAGE);
//            } else if (status == 2) {
//                JOptionPane.showMessageDialog(null, "Erro na cricao das tabelas  Banco de Dados!!", "Atenção", JOptionPane.ERROR_MESSAGE);
//            }
//        }
    }//GEN-LAST:event_jButtonInstallActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ScreenLogin frame = new ScreenLogin();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        messageAlert();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenInstall.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenInstall.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenInstall.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenInstall.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenInstall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonContato;
    private javax.swing.JButton jButtonInstall;
    private javax.swing.JButton jButtonSuportInstall;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAlert;
    // End of variables declaration//GEN-END:variables
}
